- name: Deploy container 
  hosts: server
  become: true
  gather_facts: false
  vars:
    image: 192.168.56.14:5000/docker-ssh:latest
  
  tasks:
    - name: Avvia il container
      community.docker.docker_container:
        name: docker-ssh
        image: "{{ image }}"
        state: started
        recreate: true
        published_ports:
          - "2224:22"