---
dockerfile:
  - name: rocky
    image: rockylinux/rockylinux:9
    packages:
      - sudo 
      - openssh-server
    distribution: RedHat
    host_port: 2222
    port: 22
  - name: ubuntu
    image: ubuntu:24.04
    packages:
      - sudo
      - openssh-server
    distribution: Debian
    host_port: 2223
    port: 22

user:
  name: andrea
  shell: /bin/bash
  uid: 1500

ssh_key_path: /home/{{ user.name }}/.ssh/id_key_{{ user.name }}
