FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y sudo openssh-server && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /var/run/sshd && \
    echo "PermitRootLogin no" > /etc/ssh/sshd_config.d/10-ssh_config.conf && \
    echo "PasswordAuthentication no" >> /etc/ssh/sshd_config.d/10-ssh_config.conf && \
    echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config.d/10-ssh_config.conf && \
    echo "AllowUsers andrea" >> /etc/ssh/sshd_config.d/10-ssh_config.conf

RUN useradd --uid 1500 --create-home --shell /bin/bash --groups sudo andrea && \
    echo "andrea ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/andrea && \
    chmod 440 /etc/sudoers.d/andrea && \
    mkdir -p /home/andrea/.ssh && \
    chmod 700 /home/andrea/.ssh && \
    chown andrea:andrea /home/andrea/.ssh

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D", "-e"]