---
- name: Crea l'utente 
  ansible.builtin.user:
    name: "{{ user.name }}"
    shell: "{{ user.shell }}"
    uid: "{{ user.uid}}"
    create_home: true

- name: Crea la directory .ssh dell'utente
  ansible.builtin.file:
    path: "{{ ssh_key_path | dirname }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0700'
 
- name: Genera coppia di chiavi SSH per andrea
  community.crypto.openssh_keypair:
    path: "{{ ssh_key_path }}"
    type: ed25519
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
 
- name: Crea la directory di build
  ansible.builtin.file:
    path: "/home/{{ user.name }}/build"
    state: directory
    mode: '0755'

- name: Genera il Dockerfile
  ansible.builtin.template:
    src: Dockerfile.j2
    dest: "/home/{{ user.name }}/build/Dockerfile-{{ item.name }}" 
    mode: '0644'
  loop: "{{ dockerfile }}"

- name: Rileva il container engine
  ansible.builtin.shell: command -v podman || command -v docker
  register: engine_check
  changed_when: false
  failed_when: engine_check.rc != 0

- name: Imposta container_engine
  ansible.builtin.set_fact:
    container_engine: "{{ container_engine | default(engine_check.stdout | basename) }}"

- name: Builda l'immagine e crea i container
  ansible.builtin.include_tasks: "{{ container_engine }}.yaml"
